### ISSUE TITLE
Support for bordered triangles

### ISSUE THREAD

**Issue by F21** [tilomitra/WidgetPointer#8]
Would love to see support for bordered triangles such as this one:

``` css
.arrow_box {
    position: relative;
    background: #333333;
    border: 2px solid #555555;
}
.arrow_box:after, .arrow_box:before {
    right: 100%;
    top: 50%;
    border: solid transparent;
    content: " ";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
}

.arrow_box:after {
    border-color: rgba(51, 51, 51, 0);
    border-right-color: #333333;
    border-width: 10px;
    margin-top: -10px;
}
.arrow_box:before {
    border-color: rgba(85, 85, 85, 0);
    border-right-color: #555555;
    border-width: 13px;
    margin-top: -13px;
}
```
